import {Role} from "@prisma/client";
import bcrypt from "bcrypt";
import {prisma} from "../src/infrastructure/db/prisma";


async function main() {
    const password = await bcrypt.hash("123456", 10);

    const users = [
        { email: "admin1@gmail.com", firstName: "Нурдаулет", lastName: "Беленов", surName:"Талапович" , role: Role.ADMIN ,  skills: ["React", "TypeScript" , "JavaScript" , "Express"] as const },
        {
            email: "admin2@gmail.com",
            firstName: "Айбек",
            lastName: "Нуржанов",
            surName: "Сериков",
            role: Role.ADMIN,
            skills: ["NestJS", "API design", "JWT", "Redis"] as const },
        {
            email: "admin3@gmail.com",
            firstName: "Алина",
            lastName: "Соколова",
            surName: "Громова",
            role: Role.ADMIN,
            skills: ["React", "TypeScript", "Redux"] as const },
        {
            email: "admin4@gmail.com",
            firstName: "Мадина",
            lastName: "Касымова",
            surName: "Бекенова",
            role: Role.ADMIN,
            skills: ["Prisma", "SQL", "Database design"] as const },
        {
            email: "admin5@gmail.com",
            firstName: "Илья",
            lastName: "Кузнецов",
            surName: "Рябов",
            role: Role.ADMIN,
            skills: ["Docker", "Linux", "CI/CD"] as const },
        {
            email: "admin6@gmail.com",
            firstName: "Аружан",
            lastName: "Сагындыкова",
            surName: "Ермекова",
            role: Role.ADMIN,
            skills: ["C#", ".NET", "EF Core", "SQL Server"] as const },
        {
            email: "admin7@gmail.com",
            firstName: "Максим",
            lastName: "Лебедев",
            surName: "Коновалов",
            role: Role.ADMIN,
            skills: ["GraphQL", "TypeScript", "Node.js"] as const },
        {
            email: "admin8@gmail.com",
            firstName: "Нурлан",
            lastName: "Ахметов",
            surName: "Ниязов",
            role: Role.ADMIN,
            skills: ["Kubernetes", "Docker", "Helm", "Linux"] as const },
        {
            email: "admin9@gmail.com",
            firstName: "Екатерина",
            lastName: "Федорова",
            surName: "Зимина",
            role: Role.ADMIN,
            skills: ["Python", "FastAPI", "PostgreSQL"] as const },
        {
            email: "admin10@gmail.com",
            firstName: "Данияр",
            lastName: "Тлеубердин",
            surName: "Кожахметов",
            role: Role.ADMIN,
            skills: ["Go", "Clean Architecture", "REST", "PostgreSQL"] as const },
        {
            email: "admin11@gmail.com",
            firstName: "Никита",
            lastName: "Захаров",
            surName: "Сафонов",
            role: Role.ADMIN,
            skills: ["Next.js", "React", "TypeScript"] as const },
        {
            email: "admin12@gmail.com",
            firstName: "Жанна",
            lastName: "Ергалиева",
            surName: "Муканова",
            role: Role.ADMIN,
            skills: ["QA automation", "Playwright", "TypeScript", "CI/CD"] as const },
        {
            email: "admin13@gmail.com",
            firstName: "Олег",
            lastName: "Кравцов",
            surName: "Егоров",
            role: Role.ADMIN,
            skills: ["Security", "JWT", "OAuth2", "API design"] as const },
        {
            email: "admin14@gmail.com",
            firstName: "Еркебулан",
            lastName: "Жумабеков",
            surName: "Сейдахметов",
            role: Role.ADMIN,
            skills: ["MongoDB", "Mongoose", "Node.js", "Express"] as const },
        {
            email: "admin15@gmail.com",
            firstName: "Мария",
            lastName: "Иванова",
            surName: "Тихонова",
            role: Role.ADMIN,
            skills: ["UI/UX", "Figma", "Design systems"] as const },
        {
            email: "admin16@gmail.com",
            firstName: "Айдана",
            lastName: "Турсынова",
            surName: "Жаксылыкова",
            role: Role.ADMIN,
            skills: ["React", "RTK Query", "TypeScript", "Zod"] as const },
        {
            email: "admin17@gmail.com",
            firstName: "Сергей",
            lastName: "Морозов",
            surName: "Калинин",
            role: Role.ADMIN,
            skills: ["Microservices", "Kafka", "Docker", "Observability"] as const },
        {
            email: "admin18@gmail.com",
            firstName: "Бауыржан",
            lastName: "Омаров",
            surName: "Калиев",
            role: Role.ADMIN,
            skills: ["Elasticsearch", "Kibana", "Logstash"] as const },
        {
            email: "admin19@gmail.com",
            firstName: "Анна",
            lastName: "Беляева",
            surName: "Романова",
            role: Role.ADMIN,
            skills: ["Data analysis", "SQL", "Power BI"] as const },
        {
            email: "admin20@gmail.com",
            firstName: "Санжар",
            lastName: "Кудайбергенов",
            surName: "Кенжебаев",
            role: Role.ADMIN,
            skills: ["AWS", "Terraform", "CI/CD", "Docker"] as const },
        {
            email: "admin21@gmail.com",
            firstName: "Артем",
            lastName: "Волков",
            surName: "Быков",
            role: Role.ADMIN,
            skills: ["Java", "Spring Boot", "PostgreSQL"] as const },
        {
            email: "admin22@gmail.com",
            firstName: "Айсулу",
            lastName: "Серикбаева",
            surName: "Нуртаева",
            role: Role.ADMIN,
            skills: ["Flutter", "Dart", "REST"] as const },
        {
            email: "admin23@gmail.com",
            firstName: "Виктор",
            lastName: "Семенов",
            surName: "Нестеров",
            role: Role.ADMIN,
            skills: ["SRE", "Prometheus", "Grafana", "Linux"] as const },
        {
            email: "admin24@gmail.com",
            firstName: "Раушан",
            lastName: "Алимжанова",
            surName: "Сулейменова",
            role: Role.ADMIN,
            skills: ["PostgreSQL", "Performance tuning", "SQL", "Indexing"] as const },
        {
            email: "admin25@gmail.com",
            firstName: "Павел",
            lastName: "Гусев",
            surName: "Дорофеев",
            role: Role.ADMIN,
            skills: ["Team lead", "System design", "Code review"] as const },

        {
            email: "user1@gmail.com",
            firstName: "Мирас",
            lastName: "Нурпеисов",
            surName: "Есенов",
            role: Role.USER,
            skills: ["React", "JavaScript", "HTML", "CSS"] as const },
        {
            email: "user2@gmail.com",
            firstName: "Алексей",
            lastName: "Петров",
            surName: "Куликов",
            role: Role.USER,
            skills: ["Node.js", "Express", "JWT"] as const },
        {
            email: "user3@gmail.com",
            firstName: "Алия",
            lastName: "Кенжекулова",
            surName: "Тлегенова",
            role: Role.USER,
            skills: ["TypeScript", "React", "Vite"] as const },
        {
            email: "user4@gmail.com",
            firstName: "Кирилл",
            lastName: "Сергеев",
            surName: "Макаров",
            role: Role.USER,
            skills: ["C#", ".NET", "ASP.NET Core"] as const },
        {
            email: "user5@gmail.com",
            firstName: "Динара",
            lastName: "Жолдасова",
            surName: "Куанышбаева",
            role: Role.USER,
            skills: ["SQL", "Prisma", "PostgreSQL"] as const },
        {
            email: "user6@gmail.com",
            firstName: "Ирина",
            lastName: "Смирнова",
            surName: "Козлова",
            role: Role.USER,
            skills: ["QA", "Test cases", "Bug tracking"] as const },
        {
            email: "user7@gmail.com",
            firstName: "Ержан",
            lastName: "Сейтжанов",
            surName: "Абдрахманов",
            role: Role.USER,
            skills: ["Docker", "Linux", "Nginx"] as const },
        {
            email: "user8@gmail.com",
            firstName: "Дарья",
            lastName: "Крылова",
            surName: "Воронова",
            role: Role.USER,
            skills: ["React", "Redux", "TypeScript"] as const },
        {
            email: "user9@gmail.com",
            firstName: "Темирлан",
            lastName: "Садыков",
            surName: "Рахимов",
            role: Role.USER,
            skills: ["Go", "REST", "PostgreSQL"] as const },
        {
            email: "user10@gmail.com",
            firstName: "Светлана",
            lastName: "Новикова",
            surName: "Корнеева",
            role: Role.USER,
            skills: ["UI/UX", "Figma", "Prototyping"] as const },
        {
            email: "user11@gmail.com",
            firstName: "Аслан",
            lastName: "Мухтаров",
            surName: "Калдаров",
            role: Role.USER,
            skills: ["Node.js", "Prisma", "PostgreSQL", "SQL"] as const },
        {
            email: "user12@gmail.com",
            firstName: "Роман",
            lastName: "Мельников",
            surName: "Кудряшов",
            role: Role.USER,
            skills: ["Python", "Django", "PostgreSQL"] as const },
        {
            email: "user13@gmail.com",
            firstName: "Асель",
            lastName: "Токтарова",
            surName: "Ибраева",
            role: Role.USER,
            skills: ["Data analysis", "Python", "Pandas", "SQL"] as const },
        {
            email: "user14@gmail.com",
            firstName: "Владислав",
            lastName: "Борисов",
            surName: "Силин",
            role: Role.USER,
            skills: ["Java", "Spring", "REST"] as const },
        {
            email: "user15@gmail.com",
            firstName: "Жанель",
            lastName: "Серикова",
            surName: "Асанова",
            role: Role.USER,
            skills: ["React", "RTK Query", "TypeScript"] as const },
        {
            email: "user16@gmail.com",
            firstName: "Наталья",
            lastName: "Васильева",
            surName: "Быстрова",
            role: Role.USER,
            skills: ["C#", "EF Core", "SQL Server"] as const },
        {
            email: "user17@gmail.com",
            firstName: "Ерасыл",
            lastName: "Тажибаев",
            surName: "Нурмагамбетов",
            role: Role.USER,
            skills: ["Kubernetes", "Docker", "CI/CD"] as const },
        {
            email: "user18@gmail.com",
            firstName: "Валерия",
            lastName: "Зайцева",
            surName: "Савина",
            role: Role.USER,
            skills: ["Frontend", "TypeScript", "Zod"] as const },
        {
            email: "user19@gmail.com",
            firstName: "Меруерт",
            lastName: "Есенбекова",
            surName: "Сатпаева",
            role: Role.USER,
            skills: ["PostgreSQL", "SQL", "Database design"] as const },
        {
            email: "user20@gmail.com",
            firstName: "Глеб",
            lastName: "Давыдов",
            surName: "Комаров",
            role: Role.USER,
            skills: ["Node.js", "NestJS", "API design"] as const },
        {
            email: "user21@gmail.com",
            firstName: "Нурсултан",
            lastName: "Бекетов",
            surName: "Оразбаев",
            role: Role.USER,
            skills: ["Android", "Kotlin", "REST"] as const },
        {
            email: "user22@gmail.com",
            firstName: "Оксана",
            lastName: "Куликова",
            surName: "Ершова",
            role: Role.USER,
            skills: ["QA automation", "Selenium", "Java"] as const },
        {
            email: "user23@gmail.com",
            firstName: "Сая",
            lastName: "Нурбаева",
            surName: "Турганова",
            role: Role.USER,
            skills: ["React Native", "TypeScript", "Mobile UI"] as const },
        {
            email: "user24@gmail.com",
            firstName: "Константин",
            lastName: "Белов",
            surName: "Горбачев",
            role: Role.USER,
            skills: ["Linux", "Bash", "Networking"] as const },
        {
            email: "user25@gmail.com",
            firstName: "Айгерим",
            lastName: "Сейткалиева",
            surName: "Нурсеитова",
            role: Role.USER,
            skills: ["Figma", "UI/UX", "Design systems"] as const },
        {
            email: "user26@gmail.com",
            firstName: "Евгений",
            lastName: "Карпов",
            surName: "Суханов",
            role: Role.USER,
            skills: ["C++", "Algorithms", "Data structures"] as const },
        {
            email: "user27@gmail.com",
            firstName: "Арман",
            lastName: "Кожанов",
            surName: "Садыбеков",
            role: Role.USER,
            skills: ["Node.js", "Express", "Swagger"] as const },
        {
            email: "user28@gmail.com",
            firstName: "Полина",
            lastName: "Гордеева",
            surName: "Николаева",
            role: Role.USER,
            skills: ["React", "Mantine", "TypeScript"] as const },
        {
            email: "user29@gmail.com",
            firstName: "Сункар",
            lastName: "Ильясов",
            surName: "Жанибеков",
            role: Role.USER,
            skills: ["DevOps", "Docker", "GitLab CI"] as const },
        {
            email: "user30@gmail.com",
            firstName: "Елена",
            lastName: "Мартынова",
            surName: "Киселева",
            role: Role.USER,
            skills: ["Postman", "API testing", "Swagger"] as const },
        {
            email: "user31@gmail.com",
            firstName: "Шынгыс",
            lastName: "Тлеуов",
            surName: "Ермеков",
            role: Role.USER,
            skills: ["Go", "gRPC", "Microservices"] as const },
        {
            email: "user32@gmail.com",
            firstName: "Антон",
            lastName: "Фролов",
            surName: "Тарасов",
            role: Role.USER,
            skills: ["React", "Redux Toolkit", "TypeScript"] as const },
        {
            email: "user33@gmail.com",
            firstName: "Айша",
            lastName: "Оспанова",
            surName: "Жумагалиева",
            role: Role.USER,
            skills: ["SQL", "MySQL", "Database design"] as const },
        {
            email: "user34@gmail.com",
            firstName: "Вадим",
            lastName: "Котов",
            surName: "Пахомов",
            role: Role.USER,
            skills: ["PHP", "Laravel", "MySQL"] as const },
        {
            email: "user35@gmail.com",
            firstName: "Наргиза",
            lastName: "Куатова",
            surName: "Сеитова",
            role: Role.USER,
            skills: ["React", "TypeScript", "Form validation"] as const },
        {
            email: "user36@gmail.com",
            firstName: "Тимофей",
            lastName: "Фомин",
            surName: "Михайлов",
            role: Role.USER,
            skills: ["Python", "FastAPI", "JWT"] as const },
        {
            email: "user37@gmail.com",
            firstName: "Жанат",
            lastName: "Кабылов",
            surName: "Тулегенов",
            role: Role.USER,
            skills: ["Linux", "Docker", "Kubernetes"] as const },
        {
            email: "user38@gmail.com",
            firstName: "Ксения",
            lastName: "Полякова",
            surName: "Гаврилова",
            role: Role.USER,
            skills: ["UX research", "Figma", "Wireframes"] as const },
        {
            email: "user39@gmail.com",
            firstName: "Самат",
            lastName: "Алимов",
            surName: "Сергазин",
            role: Role.USER,
            skills: ["Node.js", "Prisma", "JWT"] as const },
        {
            email: "user40@gmail.com",
            firstName: "Михаил",
            lastName: "Козырев",
            surName: "Кондратьев",
            role: Role.USER,
            skills: ["C#", "CQRS", "MediatR"] as const },
        {
            email: "user41@gmail.com",
            firstName: "Гульназ",
            lastName: "Мухамедьярова",
            surName: "Саттарова",
            role: Role.USER,
            skills: ["Data engineering", "Airflow", "SQL"] as const },
        {
            email: "user42@gmail.com",
            firstName: "Вера",
            lastName: "Андреева",
            surName: "Дьякова",
            role: Role.USER,
            skills: ["React", "Ant Design", "TypeScript"] as const },
        {
            email: "user43@gmail.com",
            firstName: "Кайрат",
            lastName: "Байжанов",
            surName: "Турысбеков",
            role: Role.USER,
            skills: ["Network security", "Linux", "OWASP"] as const },
        {
            email: "user44@gmail.com",
            firstName: "Юлия",
            lastName: "Дмитриева",
            surName: "Капустина",
            role: Role.USER,
            skills: ["HTML", "CSS", "JavaScript", "React"] as const },
        {
            email: "user45@gmail.com",
            firstName: "Акниет",
            lastName: "Калиева",
            surName: "Ержанова",
            role: Role.USER,
            skills: ["PostgreSQL", "SQL", "Migration tools"] as const },
        {
            email: "user46@gmail.com",
            firstName: "Степан",
            lastName: "Логинов",
            surName: "Панин",
            role: Role.USER,
            skills: ["Docker", "Compose", "Nginx"] as const },
        {
            email: "user47@gmail.com",
            firstName: "Амина",
            lastName: "Садыкова",
            surName: "Нургалиева",
            role: Role.USER,
            skills: ["React", "TypeScript", "i18n"] as const },
        {
            email: "user48@gmail.com",
            firstName: "Ярослав",
            lastName: "Кириллов",
            surName: "Тимошенко",
            role: Role.USER,
            skills: ["Go", "Testing", "REST"] as const },
        {
            email: "user49@gmail.com",
            firstName: "Бибигуль",
            lastName: "Куанышбаева",
            surName: "Калжанова",
            role: Role.USER,
            skills: ["C#", "ASP.NET Core", "JWT"] as const },
        {
            email: "user50@gmail.com",
            firstName: "Игорь",
            lastName: "Панов",
            surName: "Денисов",
            role: Role.USER,
            skills: ["Node.js", "Express", "Logging"] as const },
        {
            email: "user51@gmail.com",
            firstName: "Нурия",
            lastName: "Тлеубаева",
            surName: "Ахметжанова",
            role: Role.USER,
            skills: ["React", "Redux", "RTK Query"] as const },
        {
            email: "user52@gmail.com",
            firstName: "Петр",
            lastName: "Назаров",
            surName: "Кирсанов",
            role: Role.USER,
            skills: ["SQL", "PostgreSQL", "Indexing"] as const },
        {
            email: "user53@gmail.com",
            firstName: "Ермек",
            lastName: "Султанов",
            surName: "Кенесов",
            role: Role.USER,
            skills: ["JavaScript", "Node.js", "Express"] as const },
        {
            email: "user54@gmail.com",
            firstName: "Татьяна",
            lastName: "Горшкова",
            surName: "Сергеева",
            role: Role.USER,
            skills: ["Python", "Pytest", "QA automation"] as const },
        {
            email: "user55@gmail.com",
            firstName: "Айбек",
            lastName: "Оразов",
            surName: "Муратов",
            role: Role.USER,
            skills: ["NestJS", "TypeScript", "PostgreSQL"] as const },
        {
            email: "user56@gmail.com",
            firstName: "Надежда",
            lastName: "Шилова",
            surName: "Белова",
            role: Role.USER,
            skills: ["Product analytics", "SQL", "Metabase"] as const },
        {
            email: "user57@gmail.com",
            firstName: "Сауле",
            lastName: "Жаксылык",
            surName: "Есмагамбетова",
            role: Role.USER,
            skills: ["UX writing", "Design systems", "Figma"] as const },
        {
            email: "user58@gmail.com",
            firstName: "Денис",
            lastName: "Ермаков",
            surName: "Соболев",
            role: Role.USER,
            skills: ["C#", "Unit testing", "xUnit"] as const },
        {
            email: "user59@gmail.com",
            firstName: "Малика",
            lastName: "Кенесарина",
            surName: "Турсынбаева",
            role: Role.USER,
            skills: ["React", "TypeScript", "Accessibility"] as const },
        {
            email: "user60@gmail.com",
            firstName: "Виктория",
            lastName: "Баранова",
            surName: "Токарева",
            role: Role.USER,
            skills: ["Frontend", "CSS", "Responsive design"] as const },
        {
            email: "user61@gmail.com",
            firstName: "Жасулан",
            lastName: "Ермекбаев",
            surName: "Сергазиев",
            role: Role.USER,
            skills: ["Linux", "Git", "CI/CD"] as const },
        {
            email: "user62@gmail.com",
            firstName: "Руслан",
            lastName: "Грачев",
            surName: "Демидов",
            role: Role.USER,
            skills: ["Backend", "Node.js", "PostgreSQL"] as const },
        {
            email: "user63@gmail.com",
            firstName: "Гульмира",
            lastName: "Сарсенова",
            surName: "Токсанова",
            role: Role.USER,
            skills: ["SQL", "ETL", "Data quality"] as const },
        {
            email: "user64@gmail.com",
            firstName: "Станислав",
            lastName: "Копылов",
            surName: "Горин",
            role: Role.USER,
            skills: ["Docker", "Kubernetes", "Observability"] as const },
        {
            email: "user65@gmail.com",
            firstName: "Асхат",
            lastName: "Мусин",
            surName: "Нургазиев",
            role: Role.USER,
            skills: ["Go", "Concurrency", "Testing"] as const },
        {
            email: "user66@gmail.com",
            firstName: "Людмила",
            lastName: "Зотова",
            surName: "Кашина",
            role: Role.USER,
            skills: ["React", "TypeScript", "Component design"] as const },
        {
            email: "user67@gmail.com",
            firstName: "Назым",
            lastName: "Калдарова",
            surName: "Тасболатова",
            role: Role.USER,
            skills: ["C#", "EF Core", "Migrations"] as const },
        {
            email: "user68@gmail.com",
            firstName: "Андрей",
            lastName: "Трофимов",
            surName: "Ситников",
            role: Role.USER,
            skills: ["Node.js", "NestJS", "Swagger"] as const },
        {
            email: "user69@gmail.com",
            firstName: "Зарина",
            lastName: "Сулейменова",
            surName: "Жумабаева",
            role: Role.USER,
            skills: ["React", "i18n", "TypeScript", "Redux"] as const },
        {
            email: "user70@gmail.com",
            firstName: "Федор",
            lastName: "Кузьмин",
            surName: "Маслов",
            role: Role.USER,
            skills: ["Python", "SQLAlchemy", "PostgreSQL"] as const },
        {
            email: "user71@gmail.com",
            firstName: "Канат",
            lastName: "Нурмагамбетов",
            surName: "Тулеуов",
            role: Role.USER,
            skills: ["API design", "REST", "JWT"] as const },
        {
            email: "user72@gmail.com",
            firstName: "Маргарита",
            lastName: "Елисеева",
            surName: "Пирогова",
            role: Role.USER,
            skills: ["QA", "Postman", "API testing"] as const },
        {
            email: "user73@gmail.com",
            firstName: "Айсулу",
            lastName: "Баймуханова",
            surName: "Нурбекова",
            role: Role.USER,
            skills: ["React", "TypeScript", "Form handling"] as const },
        {
            email: "user74@gmail.com",
            firstName: "Владимир",
            lastName: "Курочкин",
            surName: "Плотников",
            role: Role.USER,
            skills: ["DevOps", "Terraform", "AWS"] as const },
        {
            email: "user75@gmail.com",
            firstName: "Меруерт",
            lastName: "Ержанова",
            surName: "Серикова",
            role: Role.USER,
            skills: ["PostgreSQL", "SQL", "Database design", "Prisma"] as const }
    ];

    for (const u of users) {
        await prisma.user.upsert({
            where: { email: u.email },
            update: {
                firstName: u.firstName,
                lastName: u.lastName,
                surName: u.surName,
                skills:[...u.skills],
                role: u.role,
            },
            create: {
                email: u.email,
                firstName: u.firstName,
                lastName: u.lastName,
                surName: u.surName,
                skills:[...u.skills],
                role: u.role,
                passwordHash: password,
            },
        });
    }

    console.log("Seed done");
}

main()
    .catch((e) => {
        console.error(e);
        process.exit(1);
    })
    .finally(async () => {
        await prisma.$disconnect();
    });
